apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1-springboot-deployment-jenkins-kyn
  namespace: group1-team1  # MySQLê³¼ ê°™ì€ ë„¤ì„ìŠ¤í˜ì´ìŠ¤
spec:
  replicas: 1  # ì›í•˜ëŠ” ë§Œí¼ ì„¤ì • ê°€ëŠ¥
  selecto:
    matchLabels:
      app: team1-springboot-deployment-jenkins-kyn
  template:
    metadata:
      labels:
        app: team1-springboot-deployment-jenkins-kyn
    spec:
      containers:
      - name: team1-springboot-deployment-jenkins-kyn
        image: k8s-vga-worker1:5000/team1-springboot-deployment-jenkins-kyn:latest  # ğŸ‘‰ ë¯¸ë¦¬ ë¹Œë“œí•œ Docker ì´ë¯¸ì§€ ì‚¬ìš©
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://team1-mysql-service.group1-team1.svc.cluster.local:3306/testdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "testuser"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "testpassword"